#!/bin/bash

# Complete Chain 6.5: Content Completeness Verification Workflow
# Runs all verification steps and generates missing content prompts

COURSE_ID="$1"

if [ -z "$COURSE_ID" ]; then
    echo "Usage: $0 <course-id>"
    echo "Example: $0 operating-systems"
    exit 1
fi

echo "🔗 Chain 6.5: Complete Content Verification Workflow"
echo "===================================================="
echo "📋 Course: $COURSE_ID"
echo "⏰ Started: $(date)"
echo ""

# Step 1: Basic content verification
echo "📋 STEP 1: BASIC CONTENT VERIFICATION"
echo "====================================="
if [ -f "verify-${COURSE_ID}.sh" ]; then
    ./verify-${COURSE_ID}.sh
else
    echo "⚠️  Course-specific verification script not found"
    echo "📋 Checking basic files..."
    
    if [ -f "course-generation-$COURSE_ID/course-architecture.json" ]; then
        echo "✅ Course architecture present"
    else
        echo "❌ Missing course architecture"
    fi
    
    if [ -f "course-generation-$COURSE_ID/character-profiles.json" ]; then
        echo "✅ Character profiles present"
    else
        echo "❌ Missing character profiles"
    fi
fi
echo ""

# Step 2: Live testing
echo "🧪 STEP 2: LIVE TESTING"
echo "======================="
if [ -f "test-course-live.sh" ]; then
    ./test-course-live.sh "$COURSE_ID"
else
    echo "❌ Live testing script not found"
    echo "🔧 Create test-course-live.sh to run live URL tests"
fi
echo ""

# Step 3: Topic crawling and completion
echo "🕷️  STEP 3: TOPIC CRAWLING AND AUTO-COMPLETION"
echo "=============================================="
if [ -f "crawl-and-complete-topics.sh" ]; then
    ./crawl-and-complete-topics.sh "$COURSE_ID"
else
    echo "❌ Topic crawling script not found"
    echo "🔧 Create crawl-and-complete-topics.sh to crawl topics"
fi
echo ""

# Step 4: Final status
echo "📊 STEP 4: FINAL VERIFICATION STATUS"
echo "===================================="

# Check if course is complete
if [ -f "course-verification-complete.json" ] || [ -f "course-auto-completion-success.json" ]; then
    echo "🎉 CHAIN 6.5 COMPLETE!"
    echo "✅ Course is fully verified and ready for students"
    echo ""
    echo "📁 Generated files:"
    ls -la *verification* *regenerate* 2>/dev/null || echo "No verification files found"
    echo ""
    echo "🚀 Ready to proceed to Chain 7: Course Page Generation"
    
    echo "🎉 CHAIN 6.5 AUTO-COMPLETION SUCCESSFUL!"
    echo "✅ Course content has been automatically generated"
    echo ""
    echo "📊 Auto-generation results:"
    if [ -f "topic-auto-completion-report.json" ]; then
        echo "📋 Generated topics: $(jq -r '.autoGeneratedTopics' topic-auto-completion-report.json)"
        echo "📈 Completion rate: $(jq -r '.completionRate' topic-auto-completion-report.json)%"
    fi
    echo ""
    echo "📁 Generated files:"
    ls -la *auto-completion* *verification* 2>/dev/null || echo "No completion files found"
    echo ""
    echo "🚀 Ready to proceed to Chain 7: Course Page Generation"
    echo ""
    echo "🌐 Test your auto-generated course:"
    echo "📱 Homepage: http://localhost:3000/index.html#courses"
    echo "📚 Course Detail: http://localhost:3000/course-detail.html?id=$COURSE_ID"
    echo "📖 First Topic: http://localhost:3000/topic-story.html?course=$COURSE_ID&index=0"
    
elif [ -f "course-verification-failed.json" ]; then
    echo "⚠️  CHAIN 6.5 INCOMPLETE"
    echo "❌ Issues found that need to be resolved"
    echo ""
    echo "🔧 Next steps:"
    if ls regenerate-topic-*.md 1> /dev/null 2>&1; then
        echo "1. Process generated regeneration prompts:"
        ls regenerate-topic-*.md | while read file; do
            echo "   - $file (use with Chain 4)"
        done
        echo "2. Re-run this workflow: ./run-chain-6.5-complete.sh $COURSE_ID"
        echo "3. Continue until verification passes"
    else
        echo "1. Review verification reports"
        echo "2. Fix identified issues"
        echo "3. Re-run verification"
    fi
    
else
    echo "⚠️  VERIFICATION STATUS UNKNOWN"
    echo "📋 No verification reports found"
    echo "🔧 Run individual verification steps manually"
fi

echo ""
echo "📋 CHAIN 6.5 WORKFLOW SUMMARY"
echo "============================="
echo "Course: $COURSE_ID"
echo "Completed: $(date)"
echo "Status: $(if [ -f "course-verification-complete.json" ] || [ -f "course-auto-completion-success.json" ]; then echo "✅ COMPLETE"; else echo "⚠️ NEEDS WORK"; fi)"

# Create workflow report
cat > "chain-6.5-workflow-report.json" << EOF
{
  "courseId": "$COURSE_ID",
  "workflowCompleted": "$(date -Iseconds)",
  "steps": {
    "basicVerification": "$(if [ -f "verify-${COURSE_ID}.sh" ]; then echo "executed"; else echo "skipped"; fi)",
    "liveTesting": "$(if [ -f "test-course-live.sh" ]; then echo "executed"; else echo "skipped"; fi)",
    "topicCrawling": "$(if [ -f "crawl-and-complete-topics.sh" ]; then echo "executed"; else echo "skipped"; fi)"
  },
  "finalStatus": "$(if [ -f "course-verification-complete.json" ] || [ -f "course-auto-completion-success.json" ]; then echo "COMPLETE"; else echo "INCOMPLETE"; fi)",
  "autoCompletionSuccessful": $(if [ -f "course-auto-completion-success.json" ]; then echo "true"; else echo "false"; fi),
  "topicsAutoGenerated": $(if [ -f "topic-auto-completion-report.json" ]; then jq -r '.autoGeneratedTopics' topic-auto-completion-report.json; else echo "0"; fi),
  "readyForChain7": $(if [ -f "course-verification-complete.json" ] || [ -f "course-auto-completion-success.json" ]; then echo "true"; else echo "false"; fi)
}
EOF

echo "📁 Workflow report: chain-6.5-workflow-report.json"
